const products = [
  {
    _id: '1',
    name: 'Unicorn',
    image: '/images/SoftToy.jpg',
    description:'Unicorn Soft toys for kids',
    brand: 'Amazon',
    category: 'Toys',
    price: 300,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Chess',
    image: '/images/chess.png',
    description:'Wooden Chess Board Game',
    brand: 'Balaji',
    category: 'Games',
    price: 300,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon Camera',
    image: '/images/camera.jpg',
    description:'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 10000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Light',
    image: '/images/led_light.png',
    description:'Decorative lightings for rooms',
    brand: 'Sony',
    category: 'Electronics',
    price: 500,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'SunGlasses',
    image: '/images/sunglasses.png',
    description: 'Sun Glasses Unisex',
    brand: 'Titan',
    category: 'Glaases',
    price: 2000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Watch',
    image: '/images/watch.png',
    description:'Titan Watch for women',
    brand: 'Amazon',
    category: 'Watches',
    price: 1000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Monopoly',
    image: '/images/monopoly.jpg',
    description:'Board game for children',
    brand: 'Amazon',
    category: 'Toys',
    price: 450,
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Teddy',
    image: '/images/teddy.png',
    description:'smooth teddy toy',
    brand: 'Amazon',
    category: 'Toys',
    price: 50,
    countInStock: 2,
    rating: 5,
    numReviews: 19,
  },
]

export default products
